# Generated by Django 3.0.4 on 2020-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_chapter_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Description of the course.', max_length=250),
        ),
    ]
