# Generated by Django 3.0.4 on 2020-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_remove_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
